Repository AriAri-Dong/ariari-frontend, pull requests merged in 2025-06, with the labels that each got.

#167 [Fix] Issue
  app/(auth)/auth/kakao/content/pageContent.tsx
  app/(club)/club/content/clubInfoSection.tsx
  app/(search)/search/content/mainSection.tsx
  app/(user)/user/userInfo/content/mainSection.tsx
  app/api/login/api.ts
  app/components/card/mainRecruitmentCard.tsx
  app/components/card/mainRecruitmentCardWithCarousel.tsx
  app/components/card/searchRecruitmentCard.tsx
  app/components/dropdown/postBox.tsx
  app/components/modal/school/registrationModal.tsx
  app/types/recruitment.ts
  app/utils/convertToServerFormat.ts
  app/utils/mappingProfile.ts
Labels: 🎨 Design, 🔗 Api

#170 [Chore] Query invalidation update
  app/(club)/club/activityHistory/components/activityCreateForm.tsx
  app/(club)/club/recruitment/content/clubRecruitmentContent.tsx
  app/(recruitment)/recruitment/detail/components/recruitmentSummary.tsx
  app/(recruitment)/recruitment/detail/content/clubInfo.tsx
  app/(terms)/terms/privacy/page.tsx
  app/(withdrawal)/withdrawal/page.tsx
  app/api/member/api.ts
  app/components/bar/floatingBar/recruitmentGuideFloatingBar.tsx
  app/components/card/clubWithdrawalCard.tsx
  app/components/card/myClubCard.tsx
  app/components/dropdown/clubEventDropdown.tsx
  app/hooks/club/evnet/useClubEventQuery.tsx
  app/hooks/club/my/useMyClubMutation.tsx
  app/hooks/club/useClubNoticeMutation.tsx
Labels: 🔗 Api, 🚧 Refactor

#171 [Fix] Kakao
  app/(auth)/auth/kakao/content/pageContent.tsx
Labels: 🐞 Bug

#177 [Fix] Issue
  app/(auth)/auth/kakao/content/pageContent.tsx
  app/(user)/user/interestRecruitment/content/filterSection.tsx
  app/components/modal/profileSetting/mobile/mobileProfileSetting.tsx
Labels: 🐞 Bug

#180 [Fix] Issue
  app/(auth)/auth/kakao/content/pageContent.tsx
  app/api/login/api.ts
  app/components/modal/profileSetting/step4.tsx
Labels: 🐞 Bug

#187 [Fix] Issue
  app/(club)/club/activityHistory/components/activityCreateContent.tsx
  app/(club)/club/activityHistory/components/activityCreateForm.tsx
  app/(club)/club/activityHistory/content/mainSection.tsx
  app/(home)/home/content/latestRecruitment.tsx
  app/(user)/user/club/create/content/mainSection.tsx
  app/(user)/user/interestClub/content/mainSection.tsx
  app/(user)/user/interestRecruitment/content/mainSection.tsx
  app/(user)/user/userInfo/content/mainSection.tsx
  app/api/club/activity/api.ts
  app/components/comment/comment.tsx
  app/components/dropdown/postBox.tsx
  app/components/dropdown/userDropdown.tsx
  app/components/feedback/requiredLogin.tsx
  app/components/user/user.tsx
  app/types/api.ts
  app/types/clubActivity.ts
Labels: 🐞 Bug, 🔗 Api

#190 [Fix] Create Club
  app/(user)/user/userInfo/content/mainSection.tsx
Labels: 💫 Feat, 🔗 Api

#197 [Fix] Issue
  app/(user)/user/club/create/content/mainSection.tsx
  app/(user)/user/userInfo/content/mainSection.tsx
  app/api/apiUrl.ts
  app/api/club/api.ts
  app/components/comment/comment.tsx
  app/components/comment/commentInput.tsx
  app/components/dropdown/postBox.tsx
  app/components/modal/profileSetting/mobile/mobileProfileSetting.tsx
  app/components/modal/profileSetting/profileSetting.tsx
  app/types/clubActivity.ts
Labels: 🐞 Bug, 🔗 Api

#206 [Fix] Issue
  app/(club)/club/activityHistory/components/activityCreateForm.tsx
  app/(club)/club/activityHistory/content/mainSection.tsx
Labels: 🐞 Bug

#212 [Fix] Axios Interceptors
  app/api/axiosInstance.ts
Labels: 🐞 Bug

#215 [Fix] Refresh Token
  app/api/axiosInstance.ts
  app/api/login/api.ts
Labels: 🐞 Bug
