Repository AriAri-Dong/ariari-frontend, pull requests merged in 2025-02, with the labels that each got.

#66 [Modify] Design modifications for components
  app/(club)/club/activityHistory/page.tsx
  app/(club)/club/close/page.tsx
  app/(club)/club/components/menu/leftMenu.tsx
  app/(club)/club/components/menu/mobileMenu.tsx
  app/(club)/club/components/renderField.tsx
  app/(club)/club/components/tabs/mobileTabs.tsx
  app/(club)/club/content/clubInfoSection.tsx
  app/(club)/club/content/clubInfoWrapper.tsx
  app/(club)/club/help/components/questionDropdown.tsx
  app/(club)/club/help/content/clubQuestionSection.tsx
  app/(club)/club/help/page.tsx
  app/(club)/club/leave/page.tsx
  app/(club)/club/management/activity/accounting/page.tsx
  app/(club)/club/management/activity/notice/page.tsx
  app/(club)/club/management/activity/schedule/page.tsx
  app/(club)/club/management/members/components/clubMemberCategoryBar.tsx
  app/(club)/club/management/members/components/clubMemberHeader.tsx
  app/(club)/club/management/members/components/clubMemberList.tsx
  app/(club)/club/management/members/components/invitationForm.tsx
  app/(club)/club/management/members/components/invitationFormContent.tsx
  app/(club)/club/management/members/page.tsx
  app/(club)/club/management/members/util/mapRole.ts
  app/(club)/club/management/members/util/mapStatus.ts
  app/(club)/club/management/recruitment/announcement/page.tsx
  app/(club)/club/management/recruitment/applicationForm/page.tsx
  app/(club)/club/management/recruitment/applicationStatus/page.tsx
  app/(club)/club/members/content/clubMembersSection.tsx
  app/(club)/club/members/page.tsx
  app/(club)/club/review/acceptance/page.tsx
  app/(club)/club/review/activity/page.tsx
  app/(recruitment)/recruitment/detail/content/clubInfo.tsx
  app/components/badge/dDayBadge.tsx
  app/components/bottomSheet/preview/applicationPreviewBottomSheet.tsx
  app/components/bottomSheet/report/reportBottomSheet.tsx
  app/components/bottomSheet/review/acceptanceReviewBottomSheet.tsx
  app/components/bottomSheet/review/activityReviewBottomSheet.tsx
  app/components/card/clubInfoCard.tsx
  app/components/dropdown/acceptanceReviewDropdown.tsx
  app/components/layout/layout.tsx
  app/components/tab/headerTab.tsx
  app/components/tab/subTap.tsx
  app/data/club.ts
  app/images/icon/active_vector.svg
Labels: 🎨 Design

#67 [Feat] Recruitment Create Page
  app/(club)/club/help/components/questionDropdown.tsx
  app/(club)/club/help/page.tsx
  app/(club)/club/management/members/components/clubMemberList.tsx
  app/(club)/club/management/members/components/invitationFormContent.tsx
  app/(club)/club/management/members/page.tsx
  app/(club)/club/management/members/util/mapRole.ts
  app/(club)/club/management/members/util/mapStatus.ts
  app/(club)/club/management/recruitment/create/components/RecruitmentPreviewForm.tsx
  app/(club)/club/management/recruitment/create/components/recruitmentContainer.tsx
  app/(club)/club/management/recruitment/create/content/createSection.tsx
  app/(club)/club/management/recruitment/create/content/headerSection.tsx
  app/(club)/club/management/recruitment/create/page.tsx
  app/(home)/home/content/clubRanking.tsx
  app/(recruitment)/recruitment/detail/content/clubInfo.tsx
  app/components/button/radioBtn.tsx
  app/components/button/withIconBtn/plusBtn.tsx
  app/components/card/clubRankingList.tsx
  app/components/card/guideBox.tsx
  app/components/card/recruitmentCard2.tsx
  app/components/image/imageUploade.tsx
  app/components/input/textInputWithCounter.tsx
  app/components/input/textareaWithErrortext.tsx
  app/components/layout/header.tsx
  app/components/layout/layout.tsx
  app/components/modal/notiPopUp.tsx
  app/data/clubMembers.ts
  app/data/faq.ts
  app/data/guideBox.ts
  app/data/qna.ts
  app/data/recruitment.ts
  app/images/icon/error.svg
  app/images/icon/popup/registration.svg
  app/images/icon/upload.svg
  app/images/icon/x.svg
  app/images/test/test.svg
  app/types/club.ts
  app/types/member.ts
  app/types/pageInfo.ts
  app/types/recruitment.ts
  app/utils/colorMapping.ts
  app/utils/formatDateToDot.ts
Labels: 💫 Feat

#76 [Feat] Club Page - Accounting
  app/(club)/club/management/activity/accounting/page.tsx
  app/components/bar/membershipBalanceBar.tsx
  app/components/bar/mobileMembershipBalanceBar.tsx
  app/components/bar/pointStatusBar.tsx
  app/components/bottomSheet/accountingBottomSheet.tsx
  app/components/input/customNumberInput.tsx
  app/components/layout/layout.tsx
  app/components/list/membershipBalanceList.tsx
  app/components/modal/club/accountingModal.tsx
  app/data/clubAccounting.ts
  app/images/icon/wallet.svg
  app/types/club.ts
  app/utils/formatDateToDot.ts
  app/utils/formatNumber.ts
Labels: 💫 Feat, 🎨 Design

#72 [Feat] Club Page - Notice
  app/(club)/club/components/tabs/mobileTabs.tsx
  app/(club)/club/management/activity/notice/components/clubNoticeHeader.tsx
  app/(club)/club/management/activity/notice/page.tsx
  app/(club)/club/management/members/components/clubMemberCategoryBar.tsx
  app/(club)/club/management/recruitment/applicationForm/page.tsx
  app/(club)/club/management/recruitment/applicationStatus/page.tsx
  app/(help)/help/components/mobileHeaderSection.tsx
  app/(help)/help/page.tsx
  app/components/alert/alert.tsx
  app/components/bottomSheet/notice/createNoticeBottomsheet.tsx
  app/components/button/iconBtn/roundPlusBtn.tsx
  app/components/button/radioBtn.tsx
  app/components/dropdown/clubNoticeDropdown.tsx
  app/components/dropdown/option/dotMenuDropdown.tsx
  app/components/layout/header.tsx
  app/components/layout/layout.tsx
  app/components/modal/club/notice/createNoticeModal.tsx
  app/data/club.ts
  app/data/clubNotice.ts
  app/data/profileType.ts
  app/images/icon/empty_img.svg
  app/images/icon/img_delete.svg
  app/images/icon/pin.svg
Labels: 💫 Feat, 🎨 Design

#80 [Feat] Club Recruitment Page
  app/(club)/club/recruitment/components/RecruitmentGuideBox.tsx
  app/(club)/club/recruitment/components/RecruitmentGuideForm.tsx
  app/(club)/club/recruitment/page.tsx
  app/(recruitment)/recruitment/detail/content/clubActivities.tsx
  app/components/badge/badge.tsx
  app/components/button/iconBtn/endBtn.tsx
  app/components/card/recruitmentCard.tsx
  app/components/layout/layout.tsx
  app/data/recruitment.ts
  app/images/icon/end.svg
  app/utils/formatDateToDot.ts
  tailwind.config.ts
Labels: 💫 Feat, 🎨 Design

#84 [Fix] Build Error
  app/(club)/club/recruitment/components/RecruitmentGuideBox.tsx
  app/(club)/club/recruitment/components/RecruitmentGuideForm.tsx
  app/(club)/club/recruitment/page.tsx
  app/(help)/help/page.tsx
  app/(recruitment)/recruitment/detail/content/clubActivities.tsx
  app/components/badge/badge.tsx
  app/components/button/iconBtn/endBtn.tsx
  app/components/card/recruitmentCard.tsx
  app/components/layout/layout.tsx
  app/data/profileType.ts
  app/data/recruitment.ts
  app/images/icon/end.svg
  app/utils/formatDateToDot.ts
  tailwind.config.ts
Labels: 🐞 Bug

#71 Feature/authentication
  .env
  app/(auth)/auth/kakao/content/pageContent.tsx
  app/(auth)/auth/kakao/page.tsx
  app/(club)/club/close/content/headerSection.tsx
  app/(club)/club/close/page.tsx
  app/(club)/club/withdrawal/content/headerSection.tsx
  app/(club)/club/withdrawal/page.tsx
  app/(home)/home/page.tsx
  app/(home)/home/pageContent.tsx
  app/api/apis.ts
  app/api/headerToken.ts
  app/api/index.ts
  app/auth/sign-in/page.tsx
  app/auth/sign-in/sign-in-page.tsx
  app/components/card/clubWithdrawalCard.tsx
  app/components/card/withdrawalCard.tsx
  app/components/dropdown/userDropdown.tsx
  app/components/layout/header.tsx
  app/components/layout/layout.tsx
  app/components/modal/login/loginModal.tsx
  app/components/modal/notiPopUp.tsx
  app/components/user/user.tsx
  app/data/club.ts
  app/data/withdrawal.ts
  app/home-page.tsx
  app/images/icon/popup/check.svg
  app/images/icon/popup/closed.svg
  app/images/icon/popup/leave.svg
  app/images/icon/popup/warning.svg
  app/stores/user-store.ts
  app/types/api.ts
  app/types/components/withdrawInfo.ts
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 💫 Feat
